// Generated by dts-bundle-generator v9.5.1

import React$1 from 'react';

declare const _default: (redirectUrl: string, options?: {
	asUrl?: string;
	statusCode?: number;
	params?: boolean;
}) => {
	new (props: {
		children?: React$1.ReactNode | undefined;
	}): {
		componentDidMount(): void;
		render(): import("react/jsx-runtime").JSX.Element;
		context: unknown;
		setState<K extends never>(state: {} | ((prevState: Readonly<{}>, props: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>) => {} | Pick<{}, K>) | Pick<{}, K>, callback?: () => void): void;
		forceUpdate(callback?: () => void): void;
		readonly props: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>;
		state: Readonly<{}>;
		shouldComponentUpdate?(nextProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, nextState: Readonly<{}>, nextContext: any): boolean;
		componentWillUnmount?(): void;
		componentDidCatch?(error: Error, errorInfo: React$1.ErrorInfo): void;
		getSnapshotBeforeUpdate?(prevProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, prevState: Readonly<{}>): any;
		componentDidUpdate?(prevProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, prevState: Readonly<{}>, snapshot?: any): void;
		componentWillMount?(): void;
		UNSAFE_componentWillMount?(): void;
		componentWillReceiveProps?(nextProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, nextContext: any): void;
		UNSAFE_componentWillReceiveProps?(nextProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, nextContext: any): void;
		componentWillUpdate?(nextProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, nextState: Readonly<{}>, nextContext: any): void;
		UNSAFE_componentWillUpdate?(nextProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, nextState: Readonly<{}>, nextContext: any): void;
	};
	new (props: {
		children?: React$1.ReactNode | undefined;
	}, context: any): {
		componentDidMount(): void;
		render(): import("react/jsx-runtime").JSX.Element;
		context: unknown;
		setState<K extends never>(state: {} | ((prevState: Readonly<{}>, props: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>) => {} | Pick<{}, K>) | Pick<{}, K>, callback?: () => void): void;
		forceUpdate(callback?: () => void): void;
		readonly props: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>;
		state: Readonly<{}>;
		shouldComponentUpdate?(nextProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, nextState: Readonly<{}>, nextContext: any): boolean;
		componentWillUnmount?(): void;
		componentDidCatch?(error: Error, errorInfo: React$1.ErrorInfo): void;
		getSnapshotBeforeUpdate?(prevProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, prevState: Readonly<{}>): any;
		componentDidUpdate?(prevProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, prevState: Readonly<{}>, snapshot?: any): void;
		componentWillMount?(): void;
		UNSAFE_componentWillMount?(): void;
		componentWillReceiveProps?(nextProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, nextContext: any): void;
		UNSAFE_componentWillReceiveProps?(nextProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, nextContext: any): void;
		componentWillUpdate?(nextProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, nextState: Readonly<{}>, nextContext: any): void;
		UNSAFE_componentWillUpdate?(nextProps: Readonly<{
			children?: React$1.ReactNode | undefined;
		}>, nextState: Readonly<{}>, nextContext: any): void;
	};
	getInitialProps({ res, query }: {
		res: any;
		query: any;
	}): Promise<{}>;
	contextType?: React$1.Context<any> | undefined;
	propTypes?: any;
};

export {
	_default as default,
};

export {};
