// Generated by dts-bundle-generator v4.3.0

export interface IOptions {
  asUrl: string
  statusCode: number
}
declare const _default: (
  redirectUrl: string,
  options: IOptions
) => {
  new (): {
    render(): any
  }
  getInitialProps({ res }: { res: any }): Promise<{}>
}
export default _default

export {}
